// <auto-generated/>

namespace DearImguiSharp
{
    internal static partial class LocalInterop
    {
        public static unsafe DearImguiSharp.ImVec2 CalliCdeclFuncDearImguiSharpImVec2(void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec2 CalliCdeclFuncDearImguiSharpImVec2(float param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, float param1, float param2, float param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, void *param3, void *param4, void *param5, void *param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, System.Byte param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(System.UInt32 param0, DearImguiSharp.ImVec2 param1, System.Byte param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(int param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, int param1, DearImguiSharp.ImVec2 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(System.Byte param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(float param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.Byte param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(float param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(int param0, DearImguiSharp.ImVec4 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(int param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(int param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt320(DearImguiSharp.ImVec4 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(System.UInt32 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(System.Byte param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec4 param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec4 param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec4 param4, DearImguiSharp.ImVec4 param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, int param4, DearImguiSharp.ImVec4 param5, DearImguiSharp.ImVec4 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, System.UInt32 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, System.Byte param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(float param0, DearImguiSharp.ImVec2 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, int param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, void *param3, int param4, int param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, float param3, float param4, void *param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, float param3, float param4, float param5, void *param6, void *param7, float param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, int param3, int param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, float param3, int param4, int param5, void *param6, void *param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, float param3, void *param4, void *param5, void *param6, float param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, int param3, float param4, void *param5, void *param6, void *param7, float param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, float param3, void *param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, float param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, int param2, int param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, void *param3, void *param4, void *param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, int param3, void *param4, void *param5, void *param6, float param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, void *param2, float param3, float param4, void *param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, void *param2, int param3, int param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, int param2, void *param3, void *param4, void *param5, void *param6, float param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, int param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, void *param1, void *param2, DearImguiSharp.ImVec2 param3, int param4, void *param5, void *param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, void *param3, int param4, void *param5, void *param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, float param3, void *param4, int param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, int param2, int param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, double param2, double param3, void *param4, int param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, void *param3, void *param4, void *param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, int param3, void *param4, void *param5, void *param6, int param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, int param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec4 param1, int param2, DearImguiSharp.ImVec2 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, System.Byte param1, int param2, DearImguiSharp.ImVec2 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, void *param1, int param2, DearImguiSharp.ImVec2 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, int param2, int param3, void *param4, float param5, float param6, DearImguiSharp.ImVec2 param7, int param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, void *param2, int param3, int param4, void *param5, float param6, float param7, DearImguiSharp.ImVec2 param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.Byte param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, float param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, System.Byte param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, void *param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, void *param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(int param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImVec2 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe double CalliCdeclFuncdouble(void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(int param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *param2, System.Byte param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, float param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(System.UInt32 param0, DearImguiSharp.ImVec2 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(int param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(int param0, System.Byte param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(int param0, float param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(int param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiOnceUponAFrame CalliCdeclFuncDearImguiSharpImGuiOnceUponAFrame(void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.Byte param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStoragePair CalliCdeclFuncDearImguiSharpImGuiStoragePair(System.UInt32 param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStoragePair CalliCdeclFuncDearImguiSharpImGuiStoragePair(System.UInt32 param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStoragePair CalliCdeclFuncDearImguiSharpImGuiStoragePair(System.UInt32 param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, System.UInt32 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, System.UInt32 param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *param0, System.UInt32 param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, int param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, int param1, int param2, int param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr0(void *param0, DearImguiSharp.ImVec4 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, float param1, float param2, float param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, float param2, float param3, float param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.UInt32 param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.UInt32 param3, float param4, int param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.UInt32 param3, float param4, int param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.UInt32 param3, System.UInt32 param4, System.UInt32 param5, System.UInt32 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, System.UInt32 param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, System.UInt32 param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, System.UInt32 param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, System.UInt32 param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, System.UInt32 param3, int param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, System.UInt32 param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, System.UInt32 param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, float param2, DearImguiSharp.ImVec2 param3, System.UInt32 param4, void *param5, void *param6, float param7, void *param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, int param2, System.UInt32 param3, System.Byte param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, int param2, System.UInt32 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, System.UInt32 param5, float param6, int param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, System.UInt32 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, DearImguiSharp.ImVec2 param6, DearImguiSharp.ImVec2 param7, DearImguiSharp.ImVec2 param8, DearImguiSharp.ImVec2 param9, System.UInt32 param10, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, System.UInt32 param6, float param7, int param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt32 param1, System.Byte param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, float param3, float param4, int param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, int param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, float param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, System.UInt32 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, DearImguiSharp.ImVec2 param6, DearImguiSharp.ImVec2 param7, DearImguiSharp.ImVec2 param8, System.UInt32 param9, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt16 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, void *param2, float param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, void *param2, int param3, float param4, void *param5, void *param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt16 CalliCdeclFuncSystemUInt16(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, System.UInt32 param1, int param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint0(void *param0, void *param1, System.UInt16 param2, int param3, int param4, float param5, DearImguiSharp.ImVec2 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, int param1, void *param2, void *param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, System.UInt16 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *param0, System.UInt16 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, float param2, float param3, float param4, void *param5, void *param6, void *param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, float param1, void *param2, void *param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, float param2, DearImguiSharp.ImVec2 param3, System.UInt32 param4, System.UInt16 param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, float param2, DearImguiSharp.ImVec2 param3, System.UInt32 param4, DearImguiSharp.ImVec4 param5, void *param6, void *param7, float param8, System.Byte param9, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt16 param1, float param2, float param3, float param4, float param5, float param6, float param7, float param8, float param9, float param10, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, System.UInt16 param1, System.UInt16 param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *param0, void *param1, System.UInt32 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt16 CalliCdeclFuncSystemUInt16(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, void *param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(System.Byte param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(System.UInt32 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, int param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, int param1, void *param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt64 CalliCdeclFuncSystemUInt64(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt64 CalliCdeclFuncSystemUInt64(void *param0, System.UInt64 param1, System.UInt64 param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliCdeclFuncSystemIntPtr(void *param0, void *param1, void *param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(float param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe double CalliCdeclFuncdouble(double param0, double param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec4 param1, DearImguiSharp.ImVec4 param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(float param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat0(DearImguiSharp.ImVec2 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat0(DearImguiSharp.ImVec4 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat0(DearImguiSharp.ImVec2 param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(int param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(float param0, float param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, DearImguiSharp.ImVec2 param3, float param4, float param5, float param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(float param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec1 CalliCdeclFuncDearImguiSharpImVec1(void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec1 CalliCdeclFuncDearImguiSharpImVec1(float param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec2ih CalliCdeclFuncDearImguiSharpImVec2ih(void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec2ih CalliCdeclFuncDearImguiSharpImVec2ih(short param0, short param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImVec2ih CalliCdeclFuncDearImguiSharpImVec2ih0(DearImguiSharp.ImVec2 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImRect param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImRect param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStyleMod.__Native CalliCdeclFuncDearImguiSharpImGuiStyleMod__Native(int param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStyleMod.__Native CalliCdeclFuncDearImguiSharpImGuiStyleMod__Native(int param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe DearImguiSharp.ImGuiStyleMod.__Native CalliCdeclFuncDearImguiSharpImGuiStyleMod__Native0(int param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, float param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *param0, float param1, float param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(void *param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt320(void *param0, DearImguiSharp.ImRect param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, float param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, void *param1, DearImguiSharp.ImRect param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliCdeclFuncSystemUInt32(void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(System.UInt32 param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(System.UInt32 param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImRect param0, float param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, System.Byte param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, System.UInt32 param1, DearImguiSharp.ImVec2 param2, System.Byte param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(System.UInt32 param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, void *param3, DearImguiSharp.ImRect param4, DearImguiSharp.ImRect param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(int param0, int param1, DearImguiSharp.ImRect param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe float CalliCdeclFuncfloat(int param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, int param1, int param2, float param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(float param0, float param1, float param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(System.UInt32 param0, int param1, System.UInt32 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(System.UInt32 param0, int param1, System.UInt32 param2, DearImguiSharp.ImRect param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(int param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void *CalliCdeclFuncvoidPtr(void *param0, void *param1, System.UInt32 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImRect param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, System.Byte param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImRect param1, int param2, System.UInt32 param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImRect param1, int param2, DearImguiSharp.ImVec2 param3, void *param4, System.UInt32 param5, System.UInt32 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, void *param1, void *param2, System.Byte param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, void *param1, void *param2, float param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, void *param2, void *param3, void *param4, DearImguiSharp.ImVec2 param5, void *param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, void *param3, void *param4, void *param5, DearImguiSharp.ImVec2 param6, void *param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, float param3, float param4, void *param5, void *param6, void *param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, System.UInt32 param2, System.Byte param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, DearImguiSharp.ImVec2 param1, System.UInt32 param2, float param3, DearImguiSharp.ImVec2 param4, float param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImVec2 param0, System.UInt32 param1, float param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(DearImguiSharp.ImRect param0, System.UInt32 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, System.UInt32 param2, int param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, System.UInt32 param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, float param2, int param3, System.UInt32 param4, System.UInt32 param5, System.UInt32 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImVec2 param1, DearImguiSharp.ImVec2 param2, int param3, System.UInt32 param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, DearImguiSharp.ImRect param1, System.UInt32 param2, float param3, float param4, float param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, DearImguiSharp.ImVec2 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(System.UInt32 param0, DearImguiSharp.ImVec2 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, int param1, DearImguiSharp.ImVec2 param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, int param2, void *param3, float param4, float param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, void *param2, void *param3, int param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(System.UInt32 param0, int param1, void *param2, float param3, void *param4, void *param5, void *param6, float param7, int param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, int param2, void *param3, void *param4, void *param5, void *param6, float param7, int param8, void *param9, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, int param2, void *param3, void *param4, float param5, float param6, float param7, float param8, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(System.UInt32 param0, int param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliCdeclFuncint(void *param0, int param1, int param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(int param0, int param1, void *param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte(void *param0, void *param1, int param2, void *param3, void *param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(void *param0, void *param1, void *param2, int param3, DearImguiSharp.ImVec2 param4, int param5, void *param6, void *param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.Byte CalliCdeclFuncSystemByte0(DearImguiSharp.ImRect param0, System.UInt32 param1, void *param2, int param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(int param0, void *param1, void *param2, void *param3, int param4, int param5, void *param6, float param7, float param8, DearImguiSharp.ImVec2 param9, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, int param1, int param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, System.UInt32 param5, System.UInt32 param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid0(void *param0, int param1, int param2, DearImguiSharp.ImVec2 param3, DearImguiSharp.ImVec2 param4, DearImguiSharp.ImVec2 param5, DearImguiSharp.ImVec2 param6, System.Byte param7, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, void *param2, float param3, float param4, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(void *param0, void *param1, int param2, int param3, int param4, int param5, int param6, void *funcPtr)
        {
            throw null;
        }

        public static unsafe void CalliCdeclFuncvoid(float param0, float param1, float param2, void *param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }
    }
}